export { default as BoardSize } from './BoardSize'
export { default as SwitchWordCheck } from './SwitchWordCheck'
export { default as SwitchSwapButtons } from './SwitchSwapButtons'
export { default as SwitchTheme } from './SwitchTheme'
export { default as SelectLanguage } from './SelectLanguage'
export { default as OpenTutorial } from './OpenTutorial'
